services:
  - type: web_service
    name: interviewiq-server
    env: node
    plan: starter
    branch: main
    root: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    env:
      CLIENT_URL: "https://interviewiq-client-nzo5.onrender.com"
      FRONTEND_URL: "https://interviewiq-client-nzo5.onrender.com"

static_sites:
  - type: static_site
    name: interviewiq-client
    branch: main
    root: Client
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: starter
    autoDeploy: true
    env:
      VITE_API_URL: "https://interviewiq-1-l763.onrender.com"
